# Arewa Data Science Academy
### Deep Learning Cohort2.0
### Name: Ahmad Wafiq Saad
### Title: Week 1 Solution

### Exercises Solution


00. PyTorch Fundamentals Exercises

1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on torch.Tensor.

- The documentation on torch.cuda.

### 2. Create a random tensor with shape (7, 7).

In [3]:
import tensorflow as tf

# Define the shape of the tensor
shape = (7, 7)

# Generate a random tensor with the specified shape
rand_tensor = tf.random.normal(shape)

# Print the random tensor
print(rand_tensor)

2025-01-23 11:28:04.948254: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-23 11:28:06.440434: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1737628087.026571    2876 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1737628087.225849    2876 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-23 11:28:08.582793: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

tf.Tensor(
[[ 0.37829944 -0.26755083 -0.39437693 -0.23044169  0.88813317 -1.6284449
  -0.09735168]
 [-0.3704389   1.292468    0.8932431  -1.0800607  -0.53846854  0.23086384
  -0.78866506]
 [-0.494756    1.7196975   1.2828733  -1.0599297  -1.269399    0.62080926
   0.11939997]
 [-1.365826   -2.0453062   1.1855282  -0.44859597 -1.8467904   0.74054444
  -1.8805119 ]
 [ 0.6470118   0.94279814 -2.480592   -0.22227727 -0.5672169  -0.45507312
   0.39114994]
 [ 0.9009905  -0.9908261   0.45067784  0.78786486 -0.5465258   0.52070314
  -1.8584627 ]
 [ 0.32010114  1.948287    0.16844948  1.1870337  -0.0533631   0.02572237
  -2.6609998 ]], shape=(7, 7), dtype=float32)


2025-01-23 11:28:19.971528: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:

# Define the shapes of the tensors
shape1 = (7, 7)
shape2 = (1, 7)

# Generate random tensors
tensor1 = tf.random.normal(shape1)
tensor2 = tf.random.normal(shape2)

# Transpose the second tensor
tensor2_transposed = tf.transpose(tensor2)

# Perform matrix multiplication
result = tf.matmul(tensor1, tensor2_transposed)

# Print the result
print(result)

tf.Tensor(
[[-1.8019943 ]
 [ 0.31870383]
 [-4.2884955 ]
 [ 0.24003237]
 [-1.0738826 ]
 [ 1.3627801 ]
 [ 0.7189735 ]], shape=(7, 1), dtype=float32)


### 4. Set the random seed to 0 and do 2 & 3 over again.
The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [5]:
import torch
import numpy as np

# Set the random seed
torch.manual_seed(0)
np.random.seed(0)

# Define the shapes of the tensors
shape1 = (7, 7)
shape2 = (1, 7)

# Generate random tensors
tensor1 = torch.randn(shape1)
tensor2 = torch.randn(shape2)

# Transpose the second tensor
tensor2_transposed = tensor2.T

# Perform matrix multiplication
result = torch.mm(tensor1, tensor2_transposed)

print(result)
print(result.shape)

tensor([[ 3.5168],
        [ 2.1984],
        [-1.7815],
        [ 3.8600],
        [-1.5010],
        [-1.6916],
        [-2.9352]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [6]:
import torch

# Set the random seed for CPU and GPU
torch.manual_seed(1234)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(1234)

# Define the shapes of the tensors
shape1 = (7, 7)
shape2 = (1, 7)

# Generate random tensors
tensor1 = torch.randn(shape1)
tensor2 = torch.randn(shape2)

# Transpose the second tensor
tensor2_transposed = tensor2.T

# Perform matrix multiplication
result = torch.mm(tensor1, tensor2_transposed)

print(result)
print(result.shape)

tensor([[-0.6650],
        [-1.0960],
        [ 0.5158],
        [ 1.1359],
        [-0.8528],
        [-2.9025],
        [ 1.7191]])
torch.Size([7, 1])


### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [7]:
import torch

# Set the random seed (for CPU)
torch.manual_seed(1234)

# Check for GPU availability
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:", device)
else:
    device = torch.device("cpu")
    print("Device:", device)

# Create tensors and move them to the GPU
tensor1 = torch.randn(2, 3).to(device)
tensor2 = torch.randn(2, 3).to(device)

print(tensor1)
print(tensor2)

Device: cpu
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])
tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]])


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [8]:
import torch

# Set the random seed (for CPU)
torch.manual_seed(1234)

# Check for GPU availability
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:", device)
else:
    device = torch.device("cpu")
    print("Device:", device)

# Create tensors and move them to the GPU
tensor1 = torch.randn(2, 3).to(device)
tensor2 = torch.randn(3, 2).to(device)  # Transpose tensor2 here

# Perform matrix multiplication
result = torch.mm(tensor1, tensor2)

print(result)
print(result.shape)

Device: cpu
tensor([[-0.2000,  1.1706],
        [ 0.2649, -1.3140]])
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
import torch

# Set the random seed (for CPU)
torch.manual_seed(1234)

# Check for GPU availability
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:", device)
else:
    device = torch.device("cpu")
    print("Device:", device)

# Create tensors and move them to the GPU
tensor1 = torch.randn(2, 3).to(device)
tensor2 = torch.randn(3, 2).to(device)  # Transpose tensor2 here

# Perform matrix multiplication
result = torch.mm(tensor1, tensor2)

# Find maximum and minimum values
max_value, _ = torch.max(result, dim=0)  # Find maximum value along dimension 0 (columns)
min_value, _ = torch.min(result, dim=0)  # Find minimum value along dimension 0 (columns)

print("Maximum values:", max_value)
print("Minimum values:", min_value)

Device: cpu
Maximum values: tensor([0.2649, 1.1706])
Minimum values: tensor([-0.2000, -1.3140])


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
import torch

# Set the random seed (for CPU)
torch.manual_seed(1234)

# Check for GPU availability
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:", device)
else:
    device = torch.device("cpu")
    print("Device:", device)

# Create tensors and move them to the GPU
tensor1 = torch.randn(2, 3).to(device)
tensor2 = torch.randn(3, 2).to(device)  # Transpose tensor2 here

# Perform matrix multiplication
result = torch.mm(tensor1, tensor2)

# Find maximum and minimum values
_, max_indices = torch.max(result, dim=0)  # Find indices of maximum values
_, min_indices = torch.min(result, dim=0)  # Find indices of minimum values

print("Maximum indices:", max_indices)
print("Minimum indices:", min_indices)

Device: cpu
Maximum indices: tensor([1, 0])
Minimum indices: tensor([0, 1])


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [11]:
import torch

# Set the random seed
torch.manual_seed(7)

# Create the first tensor with shape (1, 1, 1, 10)
tensor1 = torch.randn(1, 1, 1, 10)

# Print the first tensor and its shape
print(tensor1)
print(tensor1.shape)

# Remove the singleton dimensions
tensor2 = tensor1.squeeze()

# Print the second tensor and its shape
print(tensor2)
print(tensor2.shape)

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
torch.Size([1, 1, 1, 10])
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
torch.Size([10])
